name: Update copyright year(s) in license file

jobs:
  update-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        branchName: "production"
        token: ${{ secrets.TOKEN }}
  update-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        branchName: "release"
        token: ${{ secrets.TOKEN }}
